# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x05\x66leet\"\xe3\x01\n\x13\x45\x64geTelemetryPacket\x12\x0e\n\x06\x62us_id\x18\x01 \x01(\t\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x13\n\x0bobject_type\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\x12\x15\n\rvehicle_count\x18\x07 \x01(\x05\x12\x11\n\tlux_level\x18\x08 \x01(\x02\x12\x13\n\x0bvibration_g\x18\t \x01(\x02\x12\x19\n\x11network_signal_db\x18\n \x01(\x02\"\x86\x01\n\x0fHeartbeatPacket\x12\x0e\n\x06\x62us_id\x18\x01 \x01(\t\x12\x12\n\ncpu_temp_c\x18\x02 \x01(\x02\x12\x14\n\x0cram_usage_mb\x18\x03 \x01(\x02\x12\x10\n\x08yolo_fps\x18\x04 \x01(\x02\x12\x11\n\tcamera_ok\x18\x05 \x01(\x08\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"b\n\x10MediaSyncRequest\x12\x0e\n\x06\x62us_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x15\n\rclip_duration\x18\x03 \x01(\x05\x12\x11\n\tdefect_id\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDGETELEMETRYPACKET']._serialized_start=27
  _globals['_EDGETELEMETRYPACKET']._serialized_end=254
  _globals['_HEARTBEATPACKET']._serialized_start=257
  _globals['_HEARTBEATPACKET']._serialized_end=391
  _globals['_MEDIASYNCREQUEST']._serialized_start=393
  _globals['_MEDIASYNCREQUEST']._serialized_end=491
# @@protoc_insertion_point(module_scope)
